<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-7E11E8AU" ignored="1" name="Default test(failed)" tests="2" failures="2" timestamp="04 Sep 2020 04:18:07 GMT" time="0.058" errors="0">
  <testcase name="tc1" time="0.017" classname="Rerun.Manual">
    <failure type="java.lang.AssertionError" message="expected [vinothK] but found [vinoth]">
      <![CDATA[java.lang.AssertionError: expected [vinothK] but found [vinoth]
at Rerun.Manual.tc1(Manual.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- tc1 -->
  <testcase name="tc3" time="0.002" classname="Rerun.Manual">
    <failure type="java.lang.AssertionError" message="expected [sakthi] but found [vinoth]">
      <![CDATA[java.lang.AssertionError: expected [sakthi] but found [vinoth]
at Rerun.Manual.tc3(Manual.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase name="tc2" time="0.0" classname="Rerun.Manual">
    <ignored/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- Default test(failed) -->
